repos:
-   repo: https://github.com/lorenzwalthert/pre-commit-hooks
    rev: v0.0.0.9027
    hooks:
    -   id: style-files
        args: [--style_fun=tidyverse_style]
    -   id: parsable-R
    -   id: lintr
        args: [--warn-only]
    -   id: no-browser-statement
    -   id: readme-rmd-rendered
    #-   id: roxygenize
    -   id: use-tidy-description
-   repo: https://github.com/lorenzwalthert/precommit-markdown-link-check
    rev: v0.0.0.9002  # Use the sha / tag you want to point at
    hooks:
    -   id: markdown-link-check
